export const FETCH_MOVIES_REQUESTED = "FETCH_MOVIES_REQUESTED";
export const FETCH_MOVIES_SUCCEEDED = "FETCH_MOVIES_SUCCEEDED";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FILTER_MOVIES_BY_GENRE = "FILTER_MOVIES_BY_GENRE";
export const FILTER_MOVIES_BY_LANGUAGE = "FILTER_MOVIES_BY_LANGUAGE";
export const FILTER_MOVIES = "FILTER_MOVIES";


export const PARSE_DATA_REQUESTED = "PARSE_DATA_REQUESTED";
export const PARSE_DATA_SUCCESSFUL = "PARSE_DATA_SUCCESSFUL";
export const PARSE_DATA_FAILED = "PARSE_DATA_FAILED";
export const FILTER_DATA_SUCCEDED = "FILTER_DATA_SUCCEDED";
export const FILTER_INNER_DATA_SUCCEDED = "FILTER_INNER_DATA_SUCCEDED";
export const ROOT_FILTER_APPLIED = "ROOT_FILTER_APPLIED";
