export const PARSE_DATA_REQUESTED = "PARSE_DATA_REQUESTED";
export const PARSE_DATA_SUCCESSFUL = "PARSE_DATA_SUCCESSFUL";
export const PARSE_DATA_FAILED = "PARSE_DATA_FAILED";
export const FILTER_INNER_DATA_SUCCEDED = "FILTER_INNER_DATA_SUCCEDED";
export const ROOT_FILTER_APPLIED = "ROOT_FILTER_APPLIED";
